#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# This is a dedicated issue template for 2024H1 Kyuubi Code Contribution Program, all proposed
# tasks will be listed at https://github.com/orgs/apache/projects/343 after approval
#
name: 2024H1 Kyuubi Code Contribution Task
title: "[TASK][<LEVEL>] <The Task Title>"
description: Propose a task for 2024H1 Kyuubi Code Contribution Program
body:
  - type: markdown
    attributes:
      value: |
        You are very welcome to propose new task for 2024H1 Kyuubi Code Contribution Program.
        Your brilliant ideas keep Apache Kyuubi evolving.
        Please replace the placeholder `<LEVEL>` in the issue title with one of the following options:
        - TRIVIAL - it's usually for new contributors to learn the contributor process, e.g. how to cut branch,
          how to use GitHub to send PR, how to response with reviewers, the contributor should not stay at this
          stage too long.
        - EASY - tasks like minor bugs, or simple features without requirements of knowledge for whole Kyuubi
          architecture.
        - MEDIUM - tasks typical requires that contributors have knowledge on one or more Kyuubi components,
          normally, unit tests and integration tests is also required to verify the implementations.
        - CHALLENGE - tasks requires that contributors have deep knowledge on one or more Kyuubi components,
          have good logical thinking and the ability to solve complex problems, be proficient in programming
          skills or algorithms

  - type: dropdown
    id: level
    attributes:
      label: What's the level of this task?
      multiple: false
      options:
        - TRIVIAL
        - EASY
        - MEDIUM
        - CHALLENGE
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: The Code of Conduct helps create a safe space for everyone. We require that everyone agrees to it.
      options:
        - label: >
            I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
          required: true

  - type: checkboxes
    attributes:
      label: Search before creating
      options:
        - label: >
            I have searched in the [task list](https://github.com/orgs/apache/projects/343) and found no similar
            tasks.
          required: true

  - type: checkboxes
    attributes:
      label: Mentor
      description: Mentor is required for MEDIUM and CHALLENGE tasks, to guide contributors to complete the task.
      options:
        - label: >
            I have sufficient expertise on this task, and I volunteer to be a mentor of this task to guide
            contributors through the task.
          required: false

  - type: textarea
    attributes:
      label: Skill requirements
      description: What skills are required for contributors who want to take this task?
      placeholder: |
        e.g.
        - Basic knowledge on Scala programming language
        - Familiar with Apache Maven, Docker and GitHub Action
        - Basic knowledge on network programming and Apache Thrift RPC framework
        - Familiar with Apache Spark
        - ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Background and Goals
      description: What's the current problem, and what's the final status should be after the task is completed?
      placeholder: >
        Please describe the background and your goal for requesting this task.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Implementation steps
      description: How could it be implemented?
      placeholder: >
        Please list the implementation steps in as much detail as possible so that contributors who meet
        the skill requirements could complete the task quickly and independently.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: Anything else that related to this task that the contributors need to know.
      value: |
        Introduction of [2024H1 Kyuubi Code Contribution Program](https://github.com/apache/kyuubi/issues/6232)
    validations:
      required: false

  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this task form!"
